import plotting_functions as pf
from matplotlib import rcParams
from matplotlib import pyplot as plt

# Change parameters regarding the plots, e.g. default font size.
# A full list of these can be found at:
# https://matplotlib.org/stable/api/matplotlib_configuration_api.html#matplotlib.rcParams
# To change one, add another line to do e.g. rcParams['axes.linewidth'] = 2 to set the linewidth of the axes to 2
# This will affect all plots generated by this script.
rcParams['font.size'] = 16
#Load in data
data = pf.load_excel_data_for_plots(path='output_data.xlsx')

# Example histogram plots - this covers all of the plots that you specified in your initial email I think. To add
# more, add the relevant sheet name and column name to hist_plots as another pair like ['sheetname', 'colname']
hist_plots = [['Olivine data', 'Fo'],
              ['Opx data', 'Mg#'],
              ['Opx data', 'Al2O3'],
              ['Opx data', 'Cr2O3'],
              ['Opx data', 'CaO'],
              ['Cpx data', 'Mg'],
              ['Cpx data', 'Al2O3'],
              ['Cpx data', 'Cr2O3'],
              ['Cpx data', 'CaO'],
              ['Spinel data', 'Cr'],
              ['Spinel data', 'Mg']]
# for mintype, key in hist_plots:
#     # generate them without the Gaussian fit
#     pf.plot_hist(data, mintype=mintype, key=key, gaussian_fit=False)
# Example scatter plot.

pf.scatter_plot(data, 'Olivine data', 'Olivine data', var1='Si', var2='Mg',
                mintype_z='Olivine data', var3='Fe')
pf.scatter_plot(data, 'Olivine average', 'Olivine average', var1='Si', var2='Mg',
                mintype_z='Olivine average', var3='Fe', marker='o')
plt.show()
